### ISSUE TITLE
Error in loading Shuffle tools in latest XRM Toolbox

### ISSUE THREAD

**Issue by imranakram** [rappen/Xrm.Shuffle#3]
We get this error when trying to open a Shuffle tool.

![image](https://github.com/rappen/Xrm.Shuffle/assets/13014005/f25d3421-45a0-4c61-84a0-7e058918a891)

I have a branch ready with a fix, if you can give me access on this repo please

**Comment by rappen** [comment]
Whoa... It's called XrmToolBox... 😬😉
https://twitter.com/rappen/status/951009993989459969

**Comment by imranakram** [comment]
This solves the problem: https://jonasr.app/missing-xrmtoolbox-pluginsstore/
